language: ruby
rvm:
 - 2.3.0
 
services:
 - mysql
 
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
